Javascript table sort
MickeyKay/wp-dev-dashboard pull request #11
Opened 2016-10-10 16:02 UTC by toolstack

Replace the WP_List_Table sorting with client side JavaScript sorting.

2016-10-10 17:04 UTC, MickeyKay commented
@toolstack Why would you want to replace the default functionality that WP provides?

2016-10-10 17:08 UTC, toolstack commented
To avoid a page reload.

2016-10-10 17:08 UTC, toolstack commented
Also the client side sorting allows for multiple keys to be sorted on instead of just one.

2016-10-10 17:09 UTC, MickeyKay commented
This would be cool, however I would rather stick to WP core. That way if
list table sorting is ever updated there, we'll stay compatible with their
changes. I know this would be a nice to have, but my philosophy on this one
is to stick with core.

On Mon, Oct 10, 2016 at 10:08 AM, Greg Ross <notifications@github.com>
wrote:

> To avoid a page reload.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MickeyKay/wp-dev-dashboard/pull/11#issuecomment-252681060>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADCrrvpLzuSfLwg557zuiqcTIjUE5Xq7ks5qynDygaJpZM4KSuc8>
> .
>

2016-10-10 17:12 UTC, toolstack commented
The other way to do it would be to dump the WP_List_Table code all together and just use the standard classes associated with the WP_List_Table code, which would avoid any incompatibilities in the future.

2016-10-15 17:50 UTC, MickeyKay requested changes
So. . . here are my thoughts. I really like the idea of incorporating this FE sorting, however I see no reason to switch away from all of the handiness that WP_List_Table gives us. By manually outputting the table, we lose all of the native functionality and user-accessible filters/actions that are actually pretty useful. My strong preference would be to keep the WP_List_Table output mechanism, then simply unhook WP's core table JS and override with your tablesort JS.

2016-10-15 17:52 UTC, MickeyKay commented on admin/js/jquery.tablesorter.js
> +/**!
If we're going to include this file, it should definitely be minified unless `SCRIPT_DEBUG` is set to true.

2016-10-15 17:52 UTC, MickeyKay commented on admin/class-wp-dev-dashboard-admin.php
>  	public function enqueue_scripts() {
I'm realizing we should only be enqueueing these on specific admin screens. Any chance you want to add that conditional?

2016-10-15 18:52 UTC, toolstack commented
I rebased the PR and left in the original WP_List_Table code.

2016-10-15 19:03 UTC, toolstack commented on admin/js/jquery.tablesorter.js
> +/**!
Done.

2016-10-15 19:32 UTC, toolstack commented on admin/class-wp-dev-dashboard-admin.php
>  	public function enqueue_scripts() {
Done.

2016-11-09 05:45 UTC, merged